default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nutrition_dev

test:
  <<: *default
  database: nutrition_test

production:
  <<: *default
  database: nutrition
